# Generated by Django 4.2.5 on 2023-10-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppColegio', '0002_rename_docentes_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='grade',
            field=models.IntegerField(default='prueba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='subject',
            field=models.CharField(default='Matemática', max_length=30),
            preserve_default=False,
        ),
    ]
