# Generated by Django 4.2.5 on 2023-10-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppColegio', '0003_docente_grade_docente_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='grade',
        ),
    ]
