# Generated by Django 4.2.5 on 2023-10-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppColegio', '0004_remove_docente_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
