# Generated by Django 4.2.5 on 2023-10-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppColegio', '0005_docente_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='grade',
        ),
    ]
